//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Web.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account_title {
            get {
                return ResourceManager.GetString("Account.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Clients.
        /// </summary>
        internal static string AddClients_title {
            get {
                return ResourceManager.GetString("AddClients.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Delegates.
        /// </summary>
        internal static string AddDelegates_title {
            get {
                return ResourceManager.GetString("AddDelegates.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Delegates.
        /// </summary>
        internal static string ClientsDelegates_title {
            get {
                return ResourceManager.GetString("ClientsDelegates.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string Clientshdr_title {
            get {
                return ResourceManager.GetString("Clientshdr.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients List.
        /// </summary>
        internal static string Clients_title {
            get {
                return ResourceManager.GetString("Clients.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegates.
        /// </summary>
        internal static string Delegateshdr_title {
            get {
                return ResourceManager.GetString("Delegateshdr.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegates List.
        /// </summary>
        internal static string Delegates_title {
            get {
                return ResourceManager.GetString("Delegates.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        internal static string ForgetPassword_title {
            get {
                return ResourceManager.GetString("ForgetPassword.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups_title {
            get {
                return ResourceManager.GetString("Groups.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_title {
            get {
                return ResourceManager.GetString("Home.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Itemshdr_title {
            get {
                return ResourceManager.GetString("Itemshdr.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items_title {
            get {
                return ResourceManager.GetString("Items.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices Lists.
        /// </summary>
        internal static string PricesLists_title {
            get {
                return ResourceManager.GetString("PricesLists.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration_title {
            get {
                return ResourceManager.GetString("Registration.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Lists Prices.
        /// </summary>
        internal static string SetListPrices_title {
            get {
                return ResourceManager.GetString("SetListPrices.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn_title {
            get {
                return ResourceManager.GetString("SignIn.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Transactionshdr_title {
            get {
                return ResourceManager.GetString("Transactionshdr.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Transactions_title {
            get {
                return ResourceManager.GetString("Transactions.title", resourceCulture);
            }
        }
    }
}
